services:
  portainer:
    labels:
      - traefik.enable=true
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.rule=Host(`${HOST:-portainer-127-0-0-1.nip.io}`)
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
